In [9]:
import polars as pl
from datetime import datetime

In [5]:
data = pl.read_parquet('komoditas_bawang_merah_2022_2026.parquet')

In [6]:
data.head()

shape: (5, 35)
┌─────────┬─────────┬─────────┬──────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ Aceh    ┆ Bali    ┆ Banten  ┆ Bengkulu ┆ … ┆ Sumatera    ┆ Sumatera    ┆ Sumatera   ┆ Date_Param │
│ ---     ┆ ---     ┆ ---     ┆ ---      ┆   ┆ Barat       ┆ Selatan     ┆ Utara      ┆ ---        │
│ f64     ┆ f64     ┆ f64     ┆ f64      ┆   ┆ ---         ┆ ---         ┆ ---        ┆ datetime[μ │
│         ┆         ┆         ┆          ┆   ┆ f64         ┆ f64         ┆ f64        ┆ s]         │
╞═════════╪═════════╪═════════╪══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 32000.0 ┆ 22000.0 ┆ 27400.0 ┆ 30000.0  ┆ … ┆ 26250.0     ┆ 31000.0     ┆ 30150.0    ┆ 2022-01-01 │
│         ┆         ┆         ┆          ┆   ┆             ┆             ┆            ┆ 00:00:00   │
│ 32000.0 ┆ 22000.0 ┆ 27400.0 ┆ 30000.0  ┆ … ┆ 26250.0     ┆ 31000.0     ┆ 30150.0    ┆ 2022-01-02 │
│         ┆         ┆         ┆          ┆   ┆             ┆             ┆            ┆ 00:00:00   │
│ 32100.0 ┆ 21750.0 ┆ 27250.0 ┆ 29750.0  ┆ … ┆ 26250.0     ┆ 31250.0     ┆ 30500.0    ┆ 2022-01-03 │
│         ┆         ┆         ┆          ┆   ┆             ┆             ┆            ┆ 00:00:00   │
│ 31650.0 ┆ 21750.0 ┆ 27250.0 ┆ 29500.0  ┆ … ┆ 26250.0     ┆ 30250.0     ┆ 30150.0    ┆ 2022-01-04 │
│         ┆         ┆         ┆          ┆   ┆             ┆             ┆            ┆ 00:00:00   │
│ 31000.0 ┆ 22250.0 ┆ 27650.0 ┆ 29750.0  ┆ … ┆ 26250.0     ┆ 30750.0     ┆ 30500.0    ┆ 2022-01-05 │
│         ┆         ┆         ┆          ┆   ┆             ┆             ┆            ┆ 00:00:00   │
└─────────┴─────────┴─────────┴──────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [7]:
data.schema

Schema([('Aceh', Float64),
        ('Bali', Float64),
        ('Banten', Float64),
        ('Bengkulu', Float64),
        ('DI Yogyakarta', Float64),
        ('DKI Jakarta', Float64),
        ('Gorontalo', Float64),
        ('Jambi', Float64),
        ('Jawa Barat', Float64),
        ('Jawa Tengah', Float64),
        ('Jawa Timur', Float64),
        ('Kalimantan Barat', Float64),
        ('Kalimantan Selatan', Float64),
        ('Kalimantan Tengah', Float64),
        ('Kalimantan Timur', Float64),
        ('Kalimantan Utara', Float64),
        ('Kepulauan Bangka Belitung', Float64),
        ('Kepulauan Riau', Float64),
        ('Lampung', Float64),
        ('Maluku', Float64),
        ('Maluku Utara', Float64),
        ('Nusa Tenggara Barat', Float64),
        ('Nusa Tenggara Timur', Float64),
        ('Papua', Float64),
        ('Papua Barat', Float64),
        ('Riau', Float64),
        ('Sulawesi Barat', Float64),
        ('Sulawesi Selatan', Float64),
        ('Sulawesi Tengah', Float64),
        ('Sulawesi Tenggara', Float64),
        ('Sulawesi Utara', Float64),
        ('Sumatera Barat', Float64),
        ('Sumatera Selatan', Float64),
        ('Sumatera Utara', Float64),
        ('Date_Param', Datetime(time_unit='us', time_zone=None))])

In [10]:
data_s = data.filter(
    pl.col('Date_Param') == datetime.strptime('2024-10-01', '%Y-%m-%d')
)

In [11]:
data_s.head()

shape: (1, 35)
┌─────────┬─────────┬─────────┬──────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ Aceh    ┆ Bali    ┆ Banten  ┆ Bengkulu ┆ … ┆ Sumatera    ┆ Sumatera    ┆ Sumatera   ┆ Date_Param │
│ ---     ┆ ---     ┆ ---     ┆ ---      ┆   ┆ Barat       ┆ Selatan     ┆ Utara      ┆ ---        │
│ f64     ┆ f64     ┆ f64     ┆ f64      ┆   ┆ ---         ┆ ---         ┆ ---        ┆ datetime[μ │
│         ┆         ┆         ┆          ┆   ┆ f64         ┆ f64         ┆ f64        ┆ s]         │
╞═════════╪═════════╪═════════╪══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 30900.0 ┆ 24150.0 ┆ 28650.0 ┆ 28150.0  ┆ … ┆ 30650.0     ┆ 30150.0     ┆ 31450.0    ┆ 2024-10-01 │
│         ┆         ┆         ┆          ┆   ┆             ┆             ┆            ┆ 00:00:00   │
└─────────┴─────────┴─────────┴──────────┴───┴─────────────┴─────────────┴────────────┴────────────┘